name: NutritionApp-Frontend-DockerImage-CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to the Docker Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: shaiva/nutrition-app-front:latest
